### ISSUE TITLE
Missing: Third edition players kit

### ISSUE THREAD

**Issue by mirddes** [GiottoVerducci/vtescsv#1]
https://github.com/smeea/vdb/issues/32

I have 3 of them and would love to add them to my inventory with minimal effort.

**Comment by mirddes** [comment]
2	Acrobatics
1	Amusement Park Hunting Ground
1	Amaranth
4	Apportation
1	Aura Reading
1	Auspex
2	Blood Rage
4	Bonding
3	Body Arsenal
3	Bonecraft
2	Bewitching Oration
8	Blood Doll
2	Bribes
1	Canine Horde
3	Changeling
1	Celerity
2	Consanguineous Boon
4	Cloak the Gathering
3	Confusion
2	Drawing Out the Beast
1	Disputed Territory
1	Dominate
1	Dementation
1	Effective Management
1	Elder Impersonation
1	Escaped Mental Patient
3	Eyes of Chaos
7	Enhanced Senses
4	Flash
1	Festivo dello Estinto
2	Forced Awakening
2	Forgery
2	Guard Dogs
2	Glancing Blow
3	Govern the Unaligned
1	Hand Intervention
2	Harass
2	Horrid Form
1	Institution Hunting Ground
2	Increased Strength
3	Iron Glare
4	Kine Resources Contested
3	Kindred Spirits
3	Leather Jacket
1	Library Hunting Ground
4	Lost in Crowds
2	Mind Tricks
2	Nimble Feet
1	Obfuscate
6	On the Qui Vive
1	Potence
1	Palatial Estate
2	Precognition
2	Plasmic Form
2	Raven Spy
1	Revenant
2	Rumble
3	Redirection
1	Sabbat Priest
2	Secret Horde
6	Spirits Touch
1	Stunt Cycle
1	Sawed-Off Shotgun
2	Swallowed by the Night
2	Scorpion Sting
1	Strained Vitae Supply
2	Torn Signpost
3	Telepathic Counter
1	Telepathic Misdirection
1	Thaumaturgy
4	Theft of Vitae
3	Threats
4	Undead Strength
1	University Hunting Ground
1	Vicissitude
2	Voter Captivation
3	Walk of Flame
1	Wolf Companion
Crypt:
1	Alessandro Garcia
1	Armin Brenner
1	Father Juan Carlos
1	Hektor
1	Smash
1	Urraca
1	Apache Jones
1	Beauregard Krueller
1	Bloodfeud
1	Harold Zettler	Pentex Director
1	Persephone Tar-Anis
1	White Lily
1	Esoara
1	Frondator
1	Janine
1	Lucubratio
1	Paul Cordwood
1	Uta Kovacs
1	Count Vladimir Rustovich
1	Duality
1	Radu Bistri
1	Lady Zara Slatikov
1	Laika
1	Yuri Kerezenski

**Comment by GiottoVerducci** [comment]
Those starter kit (SK) starters were added to the official csv files.

**Comment by mirddes** [comment]
Absolute legends, all of you.
